version: 0.2
phases:
  install:
    commands:
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
      - unzip packer.zip
  pre_build:
    commands:
      - ./packer validate template.pkr.hcl
  build:
    commands:
      - ./packer build template.pkr.hcl
  post_build:
    commands:
      - echo "AMI build completed"
